name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm ci
      - run: |
          git config --global user.email "benjamin.p.rosen@gmail.com"
          git config --global user.name "Ben Rosen"
      - run: npm run deploy