name: Deploy to Itch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1

      - name: Push to Itch
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_TOKEN }}
          CHANNEL: browser
          ITCH_GAME: ${{ steps.package.outputs.name }}
          ITCH_USER: ${{ github.actor }}
          PACKAGE: itch/index.html
          VERSION: ${{ steps.package.outputs.version }}